services:
  bot:
    image: ghcr.io/jooble/dv-finance-exchanger:latest
    networks:
      - dv-finance-exchanger-net
    restart: always
    environment:
      - SPRING_TELEGRAM_TOKEN
      - JAVA_OPTS=-XX:MinRAMPercentage=50.0 -XX:MaxRAMPercentage=50.0 -XX:+UseZGC -XX:-ZUncommit -XX:ZCollectionInterval=30
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 240M
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - dv-finance-exchanger-mongodb-data:/data/db
    networks:
      - dv-finance-exchanger-net

    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 240M
networks:
  dv-finance-exchanger-net:
volumes:
  dv-finance-exchanger-mongodb-data:
